version: '3'

services:
  postgresql:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    command: postgres
    restart: always
    env_file:
      - .env
    networks:
      - app-network

  redis:
    image: redis:alpine3.14
    ports:
      - '6379:6379'
    restart: always
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    platform: linux/arm64/v8
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: always
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
